#!/bin/bash
#strogg 2012

#. /etc/profile

SCRIPTLOCATION="/home/garage/bin/"

#Cleanup and set up anew. Do NOT use an existing folder here. Share this via samba or NFS for remote access
mkdir -p /videolinks
cd /videolinks
rm -rf /videolinks/*

#our tree. Some folders to put more links/folders in, and some links to the root folders for manual browsing
mkdir /videolinks/a-z
mkdir /videolinks/movies
mkdir /videolinks/hdmovies
mkdir /videolinks/series
#These are my raw JBOD mounts. Each has a dvd or brrips 'source folder', and a mkv(SD) or brmkv(HD) destination
ln -s /2001 /videolinks/2001
ln -s /900 /videolinks/900
ln -s /1001 /videolinks/1001
ln -s /1000 /videolinks/1000
ln -s /2001/mkv/fitness /videolinks/fitness


#linkmaker takes required source and destination directories as parameters, as well as an optional link in our alphabetical listing
#if two titles would create the same link, an new link is created with a number appended. 

#link HD versions first, just in case we have both
#raw bluray rips 
$SCRIPTLOCATION/linkmaker /900/brrips /videolinks/hdmovies /videolinks/a-z
$SCRIPTLOCATION/linkmaker /1000/brrips /videolinks/hdmovies /videolinks/a-z

#processed bluray also in the hd folder
$SCRIPTLOCATION/linkmaker /900/brmkv /videolinks/hdmovies /videolinks/a-z
$SCRIPTLOCATION/linkmaker /1000/brmkv /videolinks/hdmovies /videolinks/a-z
$SCRIPTLOCATION/linkmaker /1001/brmkv /videolinks/hdmovies /videolinks/a-z
$SCRIPTLOCATION/linkmaker /2001/brmkv /videolinks/hdmovies /videolinks/a-z

#processed bluray again. movies contains ALL movies
$SCRIPTLOCATION/linkmaker /900/brmkv /videolinks/movies
$SCRIPTLOCATION/linkmaker /1000/brmkv /videolinks/movies
$SCRIPTLOCATION/linkmaker /1001/brmkv /videolinks/movies
$SCRIPTLOCATION/linkmaker /2001/brmkv /videolinks/movies

#Standard def movie links. we don't bother with unprocessed here
$SCRIPTLOCATION/linkmaker /2001/mkv/movies /videolinks/movies /videolinks/a-z
$SCRIPTLOCATION/linkmaker /1001/mkv/movies /videolinks/movies /videolinks/a-z
$SCRIPTLOCATION/linkmaker /1000/mkv/movies /videolinks/movies /videolinks/a-z
$SCRIPTLOCATION/linkmaker /900/mkv/movies /videolinks/movies /videolinks/a-z

#Series, raw as well as processed
$SCRIPTLOCATION/linkmaker /1000/dvd/series /videolinks/series /videolinks/a-z
$SCRIPTLOCATION/linkmaker /900/dvd/series /videolinks/series /videolinks/a-z
$SCRIPTLOCATION/linkmaker /2001/mkv/series /videolinks/series /videolinks/a-z
$SCRIPTLOCATION/linkmaker /1001/mkv/series /videolinks/series /videolinks/a-z
$SCRIPTLOCATION/linkmaker /1000/mkv/series /videolinks/series /videolinks/a-z
$SCRIPTLOCATION/linkmaker /900/mkv/series /videolinks/series /videolinks/a-z

#used to have varous 'recent directories' for finding recent rips
#mkdir /videolinks/_Recent30
#find -L /videolinks -maxdepth 1 -ctime -30 -type l -exec ln -s {} /videolinks/_Recent30 \;

#handle mp3's more simply, but keep my shit separate from my ladyfriend's
mkdir -p /musiclinks
rm -rf /musiclinks/*
mkdir /musiclinks/musictree
mkdir /musiclinks/s
mkdir /musiclinks/y

cd /musiclinks
$SCRIPTLOCATION/linkmaker /900/mp3 /musiclinks/s /musiclinks/musiclinks
$SCRIPTLOCATION/linkmaker /1000/mp3_ayun /musiclinks/y /musiclinks/musiclinks
$SCRIPTLOCATION/linkmaker /1000/mp3_ayun/Compilations /musiclinks/y /musiclinks/musiclinks
